config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :newsletters

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable # :lockable
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	before_action :set_locale
  
  	def set_locale
		logger.debug "* Accept-Language: #{request.env['HTTP_ACCEPT_LANGUAGE']}"
		I18n.locale = extract_locale_from_accept_language_header
		logger.debug "* Locale set to '#{I18n.locale}'"
	end
	
	private
		def extract_locale_from_accept_language_header
			request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
		end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_action :set_newsletter, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:index]
  # GET /newsletters
  # GET /newsletters.json
  def index
    @newsletters = Newsletter.all
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  #def show
  #end

  # GET /newsletters/new
  def new
    @newsletter = Newsletter.new
  end

  # GET /newsletters/1/edit
  #def edit
  #end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(newsletter_params)

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully created.' }
        format.json { render :show, status: :created, location: @newsletter }
      else
        format.html { render :new }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1
  # PATCH/PUT /newsletters/1.json
  #def update
   # respond_to do |format|
    #  if @newsletter.update(newsletter_params)
     #   format.html { redirect_to @newsletter, notice: 'Newsletter was successfully updated.' }
      #  format.json { render :show, status: :ok, location: @newsletter }
     # else
      #  format.html { render :edit }
       # format.json { render json: @newsletter.errors, status: :unprocessable_entity }
     # end
   # end
  #end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  #def destroy
   # @newsletter.destroy
   # respond_to do |format|
     # format.html { redirect_to newsletters_url, notice: 'Newsletter was successfully destroyed.' }
     # format.json { head :no_content }
   # end
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      @newsletter = Newsletter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_params
      params.require(:newsletter).permit(:email, :rule)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boxhiking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/newsletters/_form.html.erb
<%= form_for(@newsletter) do |f| %>
  <% if @newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

      <ul>
      <% @newsletter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :rule %><br>
    <%= f.select :rule, [['Driver', true], ['Sender', false]] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/newsletters/edit.html.erb
<h1>Editing Newsletter</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsletter %> |
<%= link_to 'Back', newsletters_path %>

app/views/newsletters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Newsletters</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Rule</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @newsletters.each do |newsletter| %>
      <tr>
        <td><%= newsletter.email %></td>
        <td><%= newsletter.rule %></td>
        <td><%= link_to 'Show', newsletter %></td>
        <td><%= link_to 'Edit', edit_newsletter_path(newsletter) %></td>
        <td><%= link_to 'Destroy', newsletter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newsletter', new_newsletter_path %>

app/views/newsletters/new.html.erb
<h1>New Newsletter</h1>

<%= render 'form' %>

<%= link_to 'Back', newsletters_path %>

app/views/newsletters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @newsletter.email %>
</p>

<p>
  <strong>Rule:</strong>
  <%= @newsletter.rule %>
</p>

<%= link_to 'Edit', edit_newsletter_path(@newsletter) %> |
<%= link_to 'Back', newsletters_path %>